### ISSUE TITLE
Split `--conf` into individual parameters?

### ISSUE THREAD

**Issue by tsalo** [paquiteau/patch-denoising#9]
@paquiteau would you be willing to split up the `--conf` string into individual parameters? E.g., `--denoising-method`, `--patch-size`, `--patch-overlap`, `--recombination-method`.

**Comment by tsalo** [comment]
I'm happy to open a PR with that change. I'm not really a fan of click, but it's totally up to you.

**Comment by Remi-Gau** [comment]
same as @tsalo: I try to stick to argparse in general but it's not a hill I will die on.
